"""Regenerate docs/data-model.md — a Mermaid ERD of the current data model.

The diagram is a PROJECTION of the code: it's built from Base.metadata, so
it cannot drift from what the app actually remembers. Never edit the output
by hand; change the models and regenerate. The /new-feature skill runs this
after every migration:

    python scripts/generate_erd.py [output-path]

Mermaid renders natively on GitHub and in Claude artifacts, so the doc is
readable wherever the repo is browsed.
"""
import sys
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND))

from app.models import Base  # noqa: E402

# SQLAlchemy type-class name → short display name. Unknown types fall back
# to the lowercased class name, which is usually readable enough.
TYPE_NAMES = {
    "UUID": "uuid",
    "String": "string",
    "Text": "text",
    "Boolean": "bool",
    "DateTime": "datetime",
    "Date": "date",
    "Integer": "int",
    "BigInteger": "int",
    "Float": "float",
    "Numeric": "decimal",
    "JSON": "json",
    "JSONB": "json",
    "LargeBinary": "bytes",
}

HEADER = """\
# Data model

<!-- AUTO-GENERATED by backend/scripts/generate_erd.py — do not edit.
     Regenerate after any model change (from backend/):
     python scripts/generate_erd.py -->

One box per database table — the things the app remembers. Reading the
diagram:

- `PK` primary key, `FK` foreign key, `UK` unique.
- An edge means "the row on the many side points at the row on the one
  side". The label shows the linking column and **what happens to the
  pointing row when the row it points at is deleted**: CASCADE = deleted
  too; SET NULL = kept, but unlinked.
- `||` exactly one · `|o` zero or one (the link is optional).
"""


def _type_name(column) -> str:
    name = type(column.type).__name__
    return TYPE_NAMES.get(name, name.lower())


def _attribute_lines(table) -> list[str]:
    lines = []
    for column in table.columns:
        keys = []
        if column.primary_key:
            keys.append("PK")
        if column.foreign_keys:
            keys.append("FK")
        if column.unique:
            keys.append("UK")
        marker = f" {','.join(keys)}" if keys else ""
        comment = ' "nullable"' if column.nullable and not column.primary_key else ""
        lines.append(f"        {_type_name(column)} {column.name}{marker}{comment}")
    return lines


def _relationship_lines(table) -> list[str]:
    lines = []
    for column in table.columns:
        for fk in column.foreign_keys:
            parent = fk.column.table.name
            ondelete = (fk.ondelete or "NO ACTION").upper()
            # Nullable FK: the link is optional (zero or one parent).
            parent_end = "|o" if column.nullable else "||"
            lines.append(
                f'    {parent} {parent_end}--o{{ {table.name} : "{column.name} · {ondelete}"'
            )
    return lines


def main() -> None:
    out = (
        Path(sys.argv[1])
        if len(sys.argv) > 1
        else BACKEND.parent / "docs" / "data-model.md"
    )
    tables = sorted(Base.metadata.tables.values(), key=lambda t: t.name)

    body = ["```mermaid", "erDiagram"]
    for table in tables:
        body.append(f"    {table.name} {{")
        body.extend(_attribute_lines(table))
        body.append("    }")
    for table in tables:
        body.extend(_relationship_lines(table))
    body.append("```")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(HEADER + "\n" + "\n".join(body) + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(tables)} tables)")


if __name__ == "__main__":
    main()
