"""margin notes and passage reads

Revision ID: 2146d6379d7a
Revises: 521dec25916f
Create Date: 2026-07-26 19:33:12.386969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2146d6379d7a'
down_revision: Union[str, None] = '521dec25916f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('passage_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notes_user_date', 'notes', ['user_id', 'date'], unique=False)
    op.create_index('ix_notes_user_passage', 'notes', ['user_id', 'passage_id'], unique=False)
    op.create_table('passage_reads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('passage_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'passage_id', 'date')
    )
    op.create_index(op.f('ix_passage_reads_passage_id'), 'passage_reads', ['passage_id'], unique=False)
    op.create_index('ix_passage_reads_user_date', 'passage_reads', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_passage_reads_user_date', table_name='passage_reads')
    op.drop_index(op.f('ix_passage_reads_passage_id'), table_name='passage_reads')
    op.drop_table('passage_reads')
    op.drop_index('ix_notes_user_passage', table_name='notes')
    op.drop_index('ix_notes_user_date', table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
