"""narration audio cache for passages and breakdowns

Revision ID: 25b943922a0f
Revises: b44951431550
Create Date: 2026-07-31 20:45:24.687934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '25b943922a0f'
down_revision: Union[str, None] = 'b44951431550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passage_audio',
    sa.Column('passage_id', sa.UUID(), nullable=False),
    sa.Column('voice', sa.String(length=50), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('passage_id', 'voice')
    )
    op.create_table('breakdown_audio',
    sa.Column('passage_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('voice', sa.String(length=50), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['passage_id', 'language'], ['passage_breakdowns.passage_id', 'passage_breakdowns.language'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('passage_id', 'language', 'voice')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('breakdown_audio')
    op.drop_table('passage_audio')
    # ### end Alembic commands ###
