"""traditions: per-tradition corpus, daily passage, user home, stamps

Revision ID: 388b812a363f
Revises: 9bf08660f363
Create Date: 2026-08-04 21:23:36.728186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '388b812a363f'
down_revision: Union[str, None] = '9bf08660f363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('tradition', sa.String(length=40), server_default='stoicism', nullable=False))
    op.add_column('daily_passages', sa.Column('tradition', sa.String(length=40), server_default='stoicism', nullable=False))
    op.drop_constraint(op.f('daily_passages_date_key'), 'daily_passages', type_='unique')
    op.create_unique_constraint('daily_passages_date_tradition_key', 'daily_passages', ['date', 'tradition'])
    op.add_column('journal_entries', sa.Column('tradition', sa.String(length=40), server_default='stoicism', nullable=False))
    op.add_column('passages', sa.Column('tradition', sa.String(length=40), server_default='stoicism', nullable=False))
    op.create_index(op.f('ix_passages_tradition'), 'passages', ['tradition'], unique=False)
    op.add_column('users', sa.Column('tradition', sa.String(length=40), server_default='stoicism', nullable=False))
    op.add_column('users', sa.Column('tradition_chosen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tradition_chosen_at')
    op.drop_column('users', 'tradition')
    op.drop_index(op.f('ix_passages_tradition'), table_name='passages')
    op.drop_column('passages', 'tradition')
    op.drop_column('journal_entries', 'tradition')
    op.drop_constraint('daily_passages_date_tradition_key', 'daily_passages', type_='unique')
    op.create_unique_constraint(op.f('daily_passages_date_key'), 'daily_passages', ['date'], postgresql_nulls_not_distinct=False)
    op.drop_column('daily_passages', 'tradition')
    op.drop_column('conversations', 'tradition')
    # ### end Alembic commands ###
