"""practice intention

Revision ID: 47e158168d1a
Revises: 2146d6379d7a
Create Date: 2026-07-26 20:32:11.124535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '47e158168d1a'
down_revision: Union[str, None] = '2146d6379d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_intentions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('minutes_per_day', sa.Integer(), nullable=False),
    sa.Column('time_of_day', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_intentions')
    # ### end Alembic commands ###
