"""word timings on narration audio

Revision ID: 71d32617caa1
Revises: cad834019566
Create Date: 2026-08-03 10:21:44.665011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '71d32617caa1'
down_revision: Union[str, None] = 'cad834019566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breakdown_audio', sa.Column('timings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('passage_audio', sa.Column('timings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passage_audio', 'timings')
    op.drop_column('breakdown_audio', 'timings')
    # ### end Alembic commands ###
