"""journal entry reflections

Revision ID: b44951431550
Revises: e4adcb680c55
Create Date: 2026-07-31 14:14:56.329892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b44951431550'
down_revision: Union[str, None] = 'e4adcb680c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('reflection', sa.Text(), nullable=True))
    op.add_column('journal_entries', sa.Column('reflection_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entries', 'reflection_model')
    op.drop_column('journal_entries', 'reflection')
    # ### end Alembic commands ###
