"""daily passages and breakdowns

Revision ID: d22761d41b80
Revises: cceba62169a3
Create Date: 2026-07-25 13:08:46.660970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd22761d41b80'
down_revision: Union[str, None] = 'cceba62169a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_passages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('passage_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_index(op.f('ix_daily_passages_passage_id'), 'daily_passages', ['passage_id'], unique=False)
    op.create_table('passage_breakdowns',
    sa.Column('passage_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('passage_id', 'language')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passage_breakdowns')
    op.drop_index(op.f('ix_daily_passages_passage_id'), table_name='daily_passages')
    op.drop_table('daily_passages')
    # ### end Alembic commands ###
